## RANDOM FUNCTION

In [1]:
import random

In [3]:
import string

In [4]:
## to genberate a random password containing alpha numeric characters 


In [5]:
pass_len = 8
characters = string.ascii_letters + string.digits + string.punctuation
password = ""

for _ in range(pass_len): # _ only used to iterate i am not using loop variable inside for loop
    random_char = random.choice(characters)

In [9]:
# pssword generator min 8 and max 12 character
characters = string.ascii_letters + string.digits + string.punctuation
pass_len = random.randint(8,12)
password = ""

for i in range(pass_len):
    random_char = random.choice(characters)
    password = password + random_char
print("password:", password)
    

password: {Vxy$7}ch?ON


In [11]:
random.choice(characters)
characters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
random.choice(characters)


'q'

In [15]:
# the plus + sign wehn dealing wirth strings it isnt adding its actually merging the two strings 
fname = "urwah"
lname = "kashaf"
fullname = fname + lname 
fullname

'urwahkashaf'

In [17]:
pass_len = 8
characters = string.ascii_letters + string.digits + string.punctuation
password = ""

for _ in range(pass_len): # _ only used to iterate i am not using loop variable inside for loop
    random_char = random.choice(characters)
    password = password + random_char
print("password:", password)
    

password: |1")Y"u,


In [19]:
# implement a random pass generator 
# only lowercase alphabets,digits and special characters($,_,.)

In [21]:
pass_len = 8
characters = string.ascii_letters + string.digits + "$_."
password = ""

for _ in range(pass_len): # _ only used to iterate i am not using loop variable inside for loop
    random_char = random.choice(characters)
    password = password + random_char
print("password:", password)

password: JXingQTR


In [23]:
import random

In [25]:
import string

## NUMPY

In [28]:
import numpy as np
# array is the collection of homogenous data types

In [30]:
std_age = [20,22,24,26,30]
type(std_age)

list

In [32]:
std_age_arr = np.array(std_age) # pyhton considers both as list to convert list to array 
type(std_age_arr)

numpy.ndarray

In [34]:
std_per = [70.7,45.8,98.65,54.34,78.43]
std_age_arr

array([20, 22, 24, 26, 30])

In [36]:
std_name = ["urwah","rida","samra","uswah"]

In [38]:
lst = ["ali", "22", "70.7"] # list contains heterogenous data types

In [40]:
age = 22
name = "ismah"
pi = 3.142
type(pi)

float

In [42]:
# 1-d array or linear array
std_age_arr

array([20, 22, 24, 26, 30])

In [44]:
#2-D array or multi dimension array 3*3

my_matrix = np.array ([[1,2,3,],[4,5,6],[7,8,9]])
type(my_matrix)

numpy.ndarray

In [46]:
#2-D array or multi dimension array 2*3

my_matrix = np.array ([[1,2,],[5,6],[8,9]])
type(my_matrix)
my_matrix

array([[1, 2],
       [5, 6],
       [8, 9]])

In [48]:
my_matrix

array([[1, 2],
       [5, 6],
       [8, 9]])